my_rails_app/config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  resources :blog_posts, path: "b"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "blog_posts#index"
end

my_rails_app/app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

my_rails_app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

my_rails_app/app/models/blog_post.rb
class BlogPost < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged

  has_rich_text :body
  has_one_attached :meta_image
  has_one_attached :banner_image
end

my_rails_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include ActiveStorage::SetCurrent
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern

  protected
    def authorize_admin!
      redirect_to root_path, alert: "You don't have permission to view this page" if !current_admin
    end
end

my_rails_app/app/controllers/blog_posts_controller.rb
class BlogPostsController < ApplicationController
  before_action :set_blog_post, only: %i[ show edit update destroy ]
  before_action :authorize_admin!, except: %i[ show index ]
  # GET /blog_posts or /blog_posts.json
  def index
    @blog_posts = BlogPost.all
  end

  # GET /blog_posts/1 or /blog_posts/1.json
  def show
  end

  # GET /blog_posts/new
  def new
    @blog_post = BlogPost.new
  end

  # GET /blog_posts/1/edit
  def edit
  end

  # POST /blog_posts or /blog_posts.json
  def create
    @blog_post = BlogPost.new(blog_post_params)

    respond_to do |format|
      if @blog_post.save
        format.html { redirect_to @blog_post, notice: "Blog post was successfully created." }
        format.json { render :show, status: :created, location: @blog_post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @blog_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blog_posts/1 or /blog_posts/1.json
  def update
    respond_to do |format|
      if @blog_post.update(blog_post_params)
        format.html { redirect_to @blog_post, notice: "Blog post was successfully updated." }
        format.json { render :show, status: :ok, location: @blog_post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @blog_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blog_posts/1 or /blog_posts/1.json
  def destroy
    @blog_post.destroy!

    respond_to do |format|
      format.html { redirect_to blog_posts_path, status: :see_other, notice: "Blog post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog_post
      @blog_post = BlogPost.friendly.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def blog_post_params
      params.expect(blog_post: [ :title, :body, :meta_description, :meta_title, :meta_image, :banner_image, :tags ])
    end
end

my_rails_app/app/helpers/application_helper.rb
module ApplicationHelper
end

my_rails_app/app/helpers/blog_posts_helper.rb
module BlogPostsHelper
end

my_rails_app/app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

my_rails_app/app/views/blog_posts/_blog_post.html.erb
<div class="w-full h-96 rounded-lg bg-gray-200 flex flex-col group">
  <div class="w-full h-64">
    <% if blog_post.banner_image.attached? %>
      <%= image_tag blog_post.banner_image, class: "h-full w-full object-cover rounded-t-lg" %>
    <% else %>
      <%= image_tag "books.jpg", class: "h-full w-full object-cover rounded-t-lg" %>
    <% end %>
  </div>

  <div class="h-14 flex-shrink-0 w-full px-4 overflow-hidden text-ellipsis"> 
    <p class="text-xl text-gray-900 overflow-hidden font-semibold"> 
      <%= blog_post.title %>
    </p>
  </div>

  <div class="w-full h-full flex items-center px-4">
    <%= link_to "Read post", blog_post, class: "px-3 py-2 rounded-lg bg-gradient-to-r from-blue-500 to-purple-500 via-indigo-500 text-indigo-50 hover:scale-105" %>
  </div>
</div>

my_rails_app/app/views/blog_posts/_form.html.erb
<%= form_with(model: blog_post, class: "contents") do |form| %>
  <% if blog_post.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-md mt-3">
      <h2><%= pluralize(blog_post.errors.count, "error") %> prohibited this blog_post from being saved:</h2>

      <ul class="list-disc ml-6">
        <% blog_post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :title %>
    <%= form.text_field :title, class: ["block shadow-sm rounded-md border outline-hidden px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": blog_post.errors[:title].none?, "border-red-400 focus:outline-red-600": blog_post.errors[:title].any?}] %>
  </div>

  <div class="my-5">
    <%= form.label :body %>
    <%= form.rich_textarea :body, class: ["block shadow-sm rounded-md border outline-hidden px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": blog_post.errors[:body].none?, "border-red-400 focus:outline-red-600": blog_post.errors[:body].any?}] %>
  </div>

  <div class="my-5">
    <%= form.label :meta_description %>
    <%= form.textarea :meta_description, rows: 4, class: ["block shadow-sm rounded-md border outline-hidden px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": blog_post.errors[:meta_description].none?, "border-red-400 focus:outline-red-600": blog_post.errors[:meta_description].any?}] %>
  </div>

  <div class="my-5">
    <%= form.label :meta_title %>
    <%= form.text_field :meta_title, class: ["block shadow-sm rounded-md border outline-hidden px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": blog_post.errors[:meta_title].none?, "border-red-400 focus:outline-red-600": blog_post.errors[:meta_title].any?}] %>
  </div>

  <div class="my-5">
    <%= form.label :meta_image %>
    <%= form.file_field :meta_image, class: ["block shadow-sm rounded-md border outline-hidden px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": blog_post.errors[:meta_image].none?, "border-red-400 focus:outline-red-600": blog_post.errors[:meta_image].any?}] %>
  </div>

  <div class="my-5">
    <%= form.label :banner_image %>
    <%= form.file_field :banner_image, class: ["block shadow-sm rounded-md border outline-hidden px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": blog_post.errors[:banner_image].none?, "border-red-400 focus:outline-red-600": blog_post.errors[:banner_image].any?}] %>
  </div>

  <div class="my-5">
    <%= form.label :tags %>
    <%= form.textarea :tags, rows: 4, class: ["block shadow-sm rounded-md border outline-hidden px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": blog_post.errors[:tags].none?, "border-red-400 focus:outline-red-600": blog_post.errors[:tags].any?}] %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

my_rails_app/app/views/blog_posts/edit.html.erb
<% content_for :title, "Editing blog post" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing blog post</h1>

  <%= render "form", blog_post: @blog_post %>

  <%= link_to "Show this blog post", @blog_post, class: "ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= link_to "Back to blog posts", blog_posts_path, class: "ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>

my_rails_app/app/views/blog_posts/index.html.erb
<% content_for :title, "Blog posts" %>

<div class="w-full">
  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Blog posts</h1>
    <%= link_to "New blog post", new_blog_post_path, class: "rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white block font-medium" if current_admin %>
  </div>

  <div id="blog_posts" class="min-w-full grid md:grid-cols-3 lg:grid-cols-4 gap-4 mt-8">
    <%= render @blog_posts %>
  </div>
</div>

my_rails_app/app/views/blog_posts/new.html.erb
<% content_for :title, "New blog post" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New blog post</h1>

  <%= render "form", blog_post: @blog_post %>

  <%= link_to "Back to blog posts", blog_posts_path, class: "ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>

my_rails_app/app/views/blog_posts/show.html.erb
<% content_for :title, @blog_post.title %>
<% content_for :head do %>
  <meta property="og:title" content="<%= @blog_post.title %>" />
  <meta property="og:type" content="article" />
  <meta property="og:url" content="<%= request.original_url %>" />
  <meta property="og:image" content="<%= @blog_post.meta_image.url if @blog_post.meta_image.attached? %>" />
  <meta name="description" content="<%= @blog_post.meta_description %>">

  <meta name="twitter:card" content="summary_large_image" />
  <meta name="twitter:site" content="@blogapp" />
  <meta name="twitter:title" content="<%= @blog_post.title %>>" />
  <meta name="twitter:description" content="<%= @blog_post.meta_description %>" />
  <meta name="twitter:image" content="<%= @blog_post.meta_image.url if @blog_post.meta_image.attached? %>" />
<% end %>

<div class="flex flex-col w-full">
  <div class="flex gap-2 mb-4">
    <%= link_to "All Posts", blog_posts_path, class: "text-xl text-gray-900 hover:underline" %>
    <%= link_to "> #{@blog_post.title}", @blog_post, class: "text-xl text-gray-900 hover:underline" %>
  </div>

  <%= image_tag(@blog_post.banner_image, class: "w-full h-64 object-cover") if @blog_post.banner_image.attached? %>

  <h1 class="font-bold text-4xl"><%= @blog_post.title %></h1>

  <div class="my-8 flex flex-col gap-4">
    <div> <%= @blog_post.body %> </div>
    <span> Tags: <%= @blog_post.tags %> </span>
  </div>

  <div class="flex items-center gap-4 mt-8">
    <%= link_to "Edit this blog post", edit_blog_post_path(@blog_post), class: "rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" if current_admin %>
    <%= link_to "Back to blog posts", blog_posts_path, class: "rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
    <%= button_to "Destroy this blog post", @blog_post, method: :delete, class: "rounded-md px-3.5 py-2.5 text-white bg-red-600 hover:bg-red-500 font-medium" if current_admin %>
  </div>
</div>

my_rails_app/app/views/layouts/_admin.html.erb
<span> Logged in as admin <%= current_admin.email %></span>

my_rails_app/app/views/layouts/_alerts.html.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

my_rails_app/app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

my_rails_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Blog" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "layouts/admin" if current_admin %>
    <%= render "layouts/alerts" %>
    <main class="container mx-auto mt-28 px-5 flex">
      <%= yield %>
    </main>
  </body>
</html>